AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploying NestJS application to AWS Lambda

Resources:
  NestJsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/src
      Handler: dist/src/main.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY