name: "staging-deployment"

on: 
  push: 
    branches: 
      - 'main'

  workflow_run:
    workflows:
      - "integration-testing"
    types: 
      - completed

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    environment: staging  # Use the staging environment for secrets

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Debug Build Output
      - name: Debug Build Output
        run: |
          echo "Inspecting build output..."
          ls -R dist
          if [ ! -f dist/src/main.js ]; then
            echo "Error: main.js not found in dist directory. Check build configuration."
            exit 1
          fi

      # Step 6: Add EC2 instance to known hosts
      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "Adding EC2 instance to known hosts..."
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      # Step 7: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 8: Fetch all secrets and update .env file
      - name: Fetch all secrets and update .env
        id: update-env
        run: |
          secret_names=$(aws secretsmanager list-secrets --query "SecretList[].Name" --output text)
          for secret_name in $secret_names; do
            secret_value=$(aws secretsmanager get-secret-value --secret-id $secret_name --query SecretString --output text)
            if echo "$secret_value" | jq -e . >/dev/null 2>&1; then
              echo "$secret_value" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read -r line; do
                key=$(echo $line | cut -d '=' -f 1)
                value=$(echo $line | cut -d '=' -f 2-)
                if grep -q "^$key=" .env; then
                  sed -i "s|^$key=.*|$key=$value|" .env
                else
                  echo "$line" >> .env
                fi
              done
            else
              secret_key=$(basename "$secret_name")
              if grep -q "^$secret_key=" .env; then
                sed -i "s|^$secret_key=.*|$secret_key=$secret_value|" .env
              else
                echo "$secret_key=$secret_value" >> .env
              fi
            fi
          done

      # Step 9: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          if [ ! -f private_key.pem ]; then
            echo "Private key file not found!"
            exit 1
          fi

          echo "Deploying to EC2 instance..."
          scp -i private_key.pem -r dist package.json package-lock.json .env ec2-user@${{ secrets.AWS_HOST }}:/home/ec2-user/study_english_data_portal

          # SSH to EC2 to run migrations and restart services
          ssh -i private_key.pem ec2-user@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ec2-user/study_english_data_portal
            npm ci --omit=dev
            
            # Step 10: Run Knex migrations using the correct environment
            echo "Running database migrations..."
            npm run migrate:staging:latest

            # Restart the application using PM2
            pm2 restart all || pm2 start "npm run start:staging" --name "study_english_data_portal"
            exit
          EOF

          echo "Deployment completed successfully."

      # Step 11: Clean up private key
      - name: Clean up private key
        run: rm -f private_key.pem