name: "staging-deployment"

on: 
  push: 
    branches: 
      - 'main'

  workflow_run:
    workflows:
      - "integration-testing"
    types: 
      - completed

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2..."
          # Add your deployment script here