name: "deployment"

on: 
  workflow_run:
    workflows:
      - "user-integration-testing"
    types: 
      - completed

jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: "Say hello"
        run: echo "Say hello"