name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci  # Faster and consistent dependency installation

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Clean and Install AWS SAM CLI
      - name: Clean and Install AWS SAM CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip curl
          curl -Lo aws-sam-cli.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip aws-sam-cli.zip -d sam-installation
          sudo ./sam-installation/install --update

      # Step 6: Force Rebuild with SAM and Deploy
      - name: Deploy with SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1
        run: |
          rm -rf .aws-sam/build  # Clean build directory to ensure fresh artifacts
          sam build --cached=false  # Force rebuild to include all changes
          sam deploy --resolve-s3 --stack-name nestjs-app --capabilities CAPABILITY_IAM --region ap-southeast-1