name: "staging-deployment"

on: 
  push: 
    branches: 
      - 'main'

  workflow_run:
    workflows:
      - "integration-testing"
    types: 
      - completed

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    environment: staging  # Use the staging environment for secrets

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Debug Build Output
      - name: Debug Build Output
        run: |
          echo "Inspecting build output..."
          ls -R dist
          if [ ! -f dist/src/main.js ]; then
            echo "Error: main.js not found in dist directory. Check build configuration."
            exit 1
          fi

      # Step 6: Add EC2 instance to known hosts
      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "Adding EC2 instance to known hosts..."
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      # Step 7: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Fetch from staging environment secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Fetch from staging environment secrets
          AWS_REGION: ${{ secrets.AWS_REGION }}  # Fetch from staging environment secrets
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USERNAME: ec2-user
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          if [ ! -f private_key.pem ]; then
            echo "Private key file not found!"
            exit 1
          fi

          echo "Deploying to EC2 instance..."
          scp -i private_key.pem -r dist package.json package-lock.json $AWS_USERNAME@$AWS_HOST:/home/ec2-user/study_english_data_portal

          ssh -i private_key.pem $AWS_USERNAME@$AWS_HOST << 'EOF'
            cd /home/ec2-user/study_english_data_portal
            npm ci --omit=dev
            pm2 restart all || pm2 start "npm run start:staging" --name "study_english_data_portal"
            exit
          EOF

          echo "Deployment completed successfully."

      # Step 8: Clean up private key
      - name: Clean up private key
        run: rm -f private_key.pem