name: "integraton-testing"
on: 
  push: 
    branches: 
      - 'main'
  pull_request: 
    branches: 
      - "main"

jobs:
  integraton-testing:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 18.17
      - name: Install dependencies
        uses: npm ci
      - name: user.controller
        run: npm run test:integration:user