name: "user-integration-testing"
on: 
  push: 
    branches: 
      - 'main'
  pull_request: 
    branches: 
      - "main"

jobs:
  user-integration-testing:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432 -U postgres; do
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Debug environment variables
        run: |
          echo "POSTGRES_USER=$POSTGRES_USER"
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
          echo "POSTGRES_DB=$POSTGRES_DB"
          echo "DATABASE_URL=$DATABASE_URL"

      - name: Run integration tests
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: npm run test:integration:user